create table public.apartment_lease_details (
  id bigint generated by default as identity primary key,
  address text not null,
  unit text not null default '',
  tenant_name text,
  activation_1 date,
  expiration_1 date,
  activation_2 date,
  expiration_2 date,
  new_rent numeric(12,2),
  current_rent numeric(12,2),
  security_deposit numeric(12,2),
  lease_status text,
  notes text,
  lease_sent text,
  lease_sent_date date,
  link text,
  rentvine_lease_id text,
  rentvine_unit_id text,
  rentvine_lease_renewal_id text,
  source text not null default 'manual',
  updated_at timestamptz not null default now(),
  unique (address, unit)
);

create index apartment_lease_details_address_idx on public.apartment_lease_details (address);

alter table public.apartment_lease_details enable row level security;

revoke all on public.apartment_lease_details from anon, authenticated;
grant all on public.apartment_lease_details to service_role;

notify pgrst, 'reload schema';
