-- Every "Upload to Rentvine" click creates a new record here instead of
-- overwriting anything -- apartment_lease_details' uploaded_via_mission_
-- control_at/_file_id columns keep tracking just the LATEST upload (shown
-- in the Rentvine tab's Lease PDF column); this table is the full history,
-- surfaced via a separate "History" link.
create table public.apartment_lease_pdf_uploads (
  id bigint generated by default as identity primary key,
  apartment_lease_details_id bigint not null references apartment_lease_details(id) on delete cascade,
  rentvine_file_id text not null,
  file_name text not null,
  uploaded_at timestamptz not null default now()
);

create index apartment_lease_pdf_uploads_apartment_idx on public.apartment_lease_pdf_uploads (apartment_lease_details_id);

alter table public.apartment_lease_pdf_uploads enable row level security;

revoke all on public.apartment_lease_pdf_uploads from anon, authenticated;
grant all on public.apartment_lease_pdf_uploads to service_role;

notify pgrst, 'reload schema';
